### PR TITLE
Feature/hacking

### PR DESCRIPTION
**Pull request by jonaprieto**
This is the beginning to set up the guidelines to avoid make a lot commits (atoms) in a pull request.
Hope it helps.

### CODE REVIEW

**Comment by jonaprieto** [comment]
Is a mess? This seems to be. Lot of commits.

**Comment by asr** [comment]
Yes, it is.

**Comment by asr** [comment]
I suggest to close this PR and to create an new one.

**Comment by asr** [comment]
Also kill the unnecessary Travis jobs please.

**Comment by asr** [comment]
I killed the Travis build associated to this PR.

**Pull request closed without merging**
