### PR TITLE
[ online-atps ] Upgrade to v0.1.1

### PR DESCRIPTION
**Pull request by jonaprieto**
@asr, This PR is to support the new version of online-atps.

Improving this tool, I added support for GHC 8.0.2, remove some dependencies, added some tests, documentation, cosmetics, typos, cabal and so on.  Maybe it can be available to publish later in hackage.

### CODE REVIEW

**Comment by asr** [comment]
Travis failed.

Also, good tools have short names and don't use hyphen in their names, but it is up to you.

**Comment by jonaprieto** [comment]
Uhmm 0k. What about `oprover` from online and prover.

**Comment by asr** [comment]
> What about `oprover` from online and prover.

:-1:

**Comment by asr** [comment]
Please delete the branch.

**Comment by jonaprieto** [comment]
It's hard to think a good name, isn't?

**Comment by asr** [comment]
Yes, it's.

**Comment by asr** [comment]
Hint: the name hasn't be an acronyms nor related to the tool.

**Pull request merged**
