### PR TITLE
add haddock documentation for getVersion function

### PR DESCRIPTION
**Pull request by jonaprieto**

### CODE REVIEW

**Review by asr — CHANGES_REQUESTED** [review]
Did you see the documentation generated by Haddock? Anyway, fix the layout problems.

**Comment by jonaprieto** [comment]
Sorry, I couldn't install Apia due to #93 to check haddock

**Comment by jonaprieto** [comment]
Sorry, but I don't get it. I'm seeing the docs after running haddock but for me it's ok. Could you fix this and maybe I can see what you are talking about. Thanks.

**Comment by asr** [comment]
> I'm seeing the docs after running haddock but for me it's ok.

You're right. Sorry.

**Pull request merged**
